// <auto-generated/>
// This code was automatically generated 
// Any changes made MANUALLY to this file will be lost.

using System;
using System.Collections.Generic;
using System.Text;

namespace IdsLib.IdsSchema.XsNodes;

internal partial class XsRestriction
{
	private static Dictionary<XsTypes.BaseTypes, List<string>> validConstraintsDictionary = new Dictionary<XsTypes.BaseTypes, List<string>>()
	{
		{XsTypes.BaseTypes.XsString, ["annotation", "pattern", "enumeration", "minLength", "maxLength", "length"] },
		{XsTypes.BaseTypes.XsAnyUri, ["annotation", "pattern", "enumeration", "minLength", "maxLength", "length"] },
		{XsTypes.BaseTypes.XsDouble, ["annotation", "pattern", "enumeration", "minExclusive", "maxExclusive", "minInclusive", "maxInclusive"] },
		{XsTypes.BaseTypes.XsFloat, ["annotation", "pattern", "enumeration", "minExclusive", "maxExclusive", "minInclusive", "maxInclusive"] },
		{XsTypes.BaseTypes.XsDuration, ["annotation", "pattern", "enumeration", "minExclusive", "maxExclusive", "minInclusive", "maxInclusive"] },
		{XsTypes.BaseTypes.XsDateTime, ["annotation", "pattern", "enumeration", "minExclusive", "maxExclusive", "minInclusive", "maxInclusive"] },
		{XsTypes.BaseTypes.XsTime, ["annotation", "pattern", "enumeration", "minExclusive", "maxExclusive", "minInclusive", "maxInclusive"] },
		{XsTypes.BaseTypes.XsDate, ["annotation", "pattern", "enumeration", "minExclusive", "maxExclusive", "minInclusive", "maxInclusive"] },
		{XsTypes.BaseTypes.XsDecimal, ["annotation", "pattern", "enumeration", "minExclusive", "maxExclusive", "minInclusive", "maxInclusive"] },
		{XsTypes.BaseTypes.XsBoolean, ["annotation", "pattern"] },
		{XsTypes.BaseTypes.XsInteger, ["annotation", "pattern", "enumeration", "maxInclusive", "maxExclusive", "minInclusive", "minExclusive"] },
	};
}
