// <auto-generated/>
// This code was automatically generated with information from Xbim.Essentials 6.0.0.438.
// Any changes made to this file will be lost.

using System;
using System.Collections.Generic;

namespace IdsLib.IfcSchema;

public partial class SchemaInfo
{
    /// <summary>
    /// The names of classes across all schemas.
    /// </summary>
    public IEnumerable<PartOfRelationInformation> AllPartOfRelations
    {
        get
        {
            if (Version == IfcSchemaVersions.Ifc2x3)
            {
                yield return new PartOfRelationInformation("IFCRELAGGREGATES", "IFCOBJECTDEFINITION", "IFCOBJECTDEFINITION");
                yield return new PartOfRelationInformation("IFCRELASSIGNSTOGROUP", "IFCGROUP", "IFCOBJECTDEFINITION");
                yield return new PartOfRelationInformation("IFCRELCONTAINEDINSPATIALSTRUCTURE", "IFCSPATIALSTRUCTUREELEMENT", "IFCPRODUCT");
                yield return new PartOfRelationInformation("IFCRELNESTS", "IFCOBJECTDEFINITION", "IFCOBJECTDEFINITION");
                yield return new PartOfRelationInformation("IFCRELVOIDSELEMENT", "IFCELEMENT", "IFCFEATUREELEMENTSUBTRACTION");
                yield return new PartOfRelationInformation("IFCRELFILLSELEMENT", "IFCOPENINGELEMENT", "IFCELEMENT");
            }
            if (Version == IfcSchemaVersions.Ifc4)
            {
                yield return new PartOfRelationInformation("IFCRELAGGREGATES", "IFCOBJECTDEFINITION", "IFCOBJECTDEFINITION");
                yield return new PartOfRelationInformation("IFCRELASSIGNSTOGROUP", "IFCGROUP", "IFCOBJECTDEFINITION");
                yield return new PartOfRelationInformation("IFCRELCONTAINEDINSPATIALSTRUCTURE", "IFCSPATIALELEMENT", "IFCPRODUCT");
                yield return new PartOfRelationInformation("IFCRELNESTS", "IFCOBJECTDEFINITION", "IFCOBJECTDEFINITION");
                yield return new PartOfRelationInformation("IFCRELVOIDSELEMENT", "IFCELEMENT", "IFCFEATUREELEMENTSUBTRACTION");
                yield return new PartOfRelationInformation("IFCRELFILLSELEMENT", "IFCOPENINGELEMENT", "IFCELEMENT");
            }
            if (Version == IfcSchemaVersions.Ifc4x3)
            {
                yield return new PartOfRelationInformation("IFCRELAGGREGATES", "IFCOBJECTDEFINITION", "IFCOBJECTDEFINITION");
                yield return new PartOfRelationInformation("IFCRELASSIGNSTOGROUP", "IFCGROUP", "IFCOBJECTDEFINITION");
                yield return new PartOfRelationInformation("IFCRELCONTAINEDINSPATIALSTRUCTURE", "IFCSPATIALELEMENT", "IFCPRODUCT");
                yield return new PartOfRelationInformation("IFCRELNESTS", "IFCOBJECTDEFINITION", "IFCOBJECTDEFINITION");
                yield return new PartOfRelationInformation("IFCRELVOIDSELEMENT", "IFCELEMENT", "IFCFEATUREELEMENTSUBTRACTION");
                yield return new PartOfRelationInformation("IFCRELFILLSELEMENT", "IFCOPENINGELEMENT", "IFCELEMENT");
            }
        }
    }
}

