// <auto-generated/>
// This code was automatically generated with information from Xbim.Essentials 5.9.0.408.
// Any changes made to this file will be lost.

using System;
using System.Collections.Generic;

namespace IdsLib.IfcSchema
{
    public partial class SchemaInfo
    {
        /// <summary>
        /// The names of classes across all schemas.
        /// </summary>
        public static IEnumerable<IfcMeasureInformation> AllMeasures
        {
            get
            {
               yield return new IfcMeasureInformation("IFCACCELERATIONMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCAMOUNTOFSUBSTANCEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCANGULARVELOCITYMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCAREADENSITYMEASURE", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCAREAMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCBINARY", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCBOOLEAN", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCCOMPLEXNUMBER", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCCOUNTMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCDATE", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCDATETIME", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCDESCRIPTIVEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCDURATION", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCDYNAMICVISCOSITYMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCELECTRICCAPACITANCEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCELECTRICCHARGEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCELECTRICCONDUCTANCEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCELECTRICCURRENTMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCELECTRICRESISTANCEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCELECTRICVOLTAGEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCENERGYMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCFONTSTYLE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCFONTVARIANT", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCFONTWEIGHT", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCFORCEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCFREQUENCYMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCGLOBALLYUNIQUEID", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCHEATFLUXDENSITYMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCHEATINGVALUEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCIDENTIFIER", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCILLUMINANCEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCINDUCTANCEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCINTEGER", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCINTEGERCOUNTRATEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCIONCONCENTRATIONMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCISOTHERMALMOISTURECAPACITYMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCLABEL", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCLENGTHMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCLINEARVELOCITYMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCLOGICAL", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCLUMINOUSFLUXMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCLUMINOUSINTENSITYMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCMASSDENSITYMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCMASSFLOWRATEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCMASSMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCMASSPERLENGTHMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCMODULUSOFELASTICITYMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCMOISTUREDIFFUSIVITYMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCMOLECULARWEIGHTMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCMOMENTOFINERTIAMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCNONNEGATIVELENGTHMEASURE", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCNORMALISEDRATIOMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCNUMERICMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCPHMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCPLANARFORCEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCPLANEANGLEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCPOSITIVEINTEGER", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCPOSITIVELENGTHMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCPOSITIVEPLANEANGLEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCPOSITIVERATIOMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCPOWERMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCPRESENTABLETEXT", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCPRESSUREMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCRADIOACTIVITYMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCRATIOMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCREAL", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCROTATIONALFREQUENCYMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCSECTIONMODULUSMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCSOUNDPOWERLEVELMEASURE", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCSOUNDPOWERMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCSOUNDPRESSUREMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCSPECIFICHEATCAPACITYMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCTEMPERATURERATEOFCHANGEMEASURE", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCTEXT", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCTEXTALIGNMENT", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCTEXTDECORATION", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCTEXTFONTNAME", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCTEXTTRANSFORMATION", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCTHERMALCONDUCTIVITYMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCTHERMALEXPANSIONCOEFFICIENTMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCTHERMALRESISTANCEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCTHERMALTRANSMITTANCEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCTHERMODYNAMICTEMPERATUREMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCTIME", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCTIMEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCTIMESTAMP", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCTORQUEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCURIREFERENCE", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCVAPORPERMEABILITYMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCVOLUMEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCVOLUMETRICFLOWRATEMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCWARPINGCONSTANTMEASURE", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IFCWELLKNOWNTEXTLITERAL", new[] { "Ifc4x3" });
            }
        }
    }
}

