// This is manually generated, we don't have the list programmatically for ifc2x3

namespace IdsLib.IfcSchema;

public partial class SchemaInfo
{
	static partial void GetRelationTypesIFC2x3(SchemaInfo schema)
	{
		schema.AddRelationType("IFCDISTRIBUTIONCHAMBERELEMENT", "IFCDISTRIBUTIONCHAMBERELEMENTTYPE");
		schema.AddRelationType("IFCENERGYCONVERSIONDEVICE", "IFCENERGYCONVERSIONDEVICETYPE");
		schema.AddRelationType("IFCSPACE", "IFCSPACETYPE");
		schema.AddRelationType("IFCCURTAINWALL", "IFCCURTAINWALLTYPE");
		schema.AddRelationType("IFCMECHANICALFASTENER", "IFCMECHANICALFASTENERTYPE");
		schema.AddRelationType("IFCRAMPFLIGHT", "IFCRAMPFLIGHTTYPE");
		schema.AddRelationType("IFCFASTENER", "IFCFASTENERTYPE");
		schema.AddRelationType("IFCFLOWTERMINAL", "IFCFLOWTERMINALTYPE");
		schema.AddRelationType("IFCFLOWTREATMENTDEVICE", "IFCFLOWTREATMENTDEVICETYPE");
		schema.AddRelationType("IFCFURNISHINGELEMENT", "IFCFURNISHINGELEMENTTYPE");
		schema.AddRelationType("IFCSLAB", "IFCSLABTYPE");
		schema.AddRelationType("IFCBUILDINGELEMENTPROXY", "IFCBUILDINGELEMENTPROXYTYPE");
		schema.AddRelationType("IFCDISCRETEACCESSORY", "IFCDISCRETEACCESSORYTYPE");
		schema.AddRelationType("IFCSPATIALSTRUCTUREELEMENT", "IFCSPATIALSTRUCTUREELEMENTTYPE");
		schema.AddRelationType("IFCFLOWCONTROLLER", "IFCFLOWCONTROLLERTYPE");
		schema.AddRelationType("IFCMEMBER", "IFCMEMBERTYPE");
		schema.AddRelationType("IFCELEMENT", "IFCELEMENTTYPE");
		schema.AddRelationType("IFCELEMENTCOMPONENT", "IFCELEMENTCOMPONENTTYPE");
		schema.AddRelationType("IFCBUILDINGELEMENT", "IFCBUILDINGELEMENTTYPE");
		schema.AddRelationType("IFCCOVERING", "IFCCOVERINGTYPE");
		schema.AddRelationType("IFCPLATE", "IFCPLATETYPE");
		schema.AddRelationType("IFCSTAIRFLIGHT", "IFCSTAIRFLIGHTTYPE");
		schema.AddRelationType("IFCFLOWMOVINGDEVICE", "IFCFLOWMOVINGDEVICETYPE");
		schema.AddRelationType("IFCBEAM", "IFCBEAMTYPE");
		schema.AddRelationType("IFCCOLUMN", "IFCCOLUMNTYPE");
		schema.AddRelationType("IFCRAILING", "IFCRAILINGTYPE");
		schema.AddRelationType("IFCFLOWFITTING", "IFCFLOWFITTINGTYPE");
		schema.AddRelationType("IFCWALL", "IFCWALLTYPE");
		schema.AddRelationType("IFCDISTRIBUTIONCONTROLELEMENT", "IFCDISTRIBUTIONCONTROLELEMENTTYPE");
		schema.AddRelationType("IFCDISTRIBUTIONELEMENT", "IFCDISTRIBUTIONELEMENTTYPE");
		schema.AddRelationType("IFCDISTRIBUTIONFLOWELEMENT", "IFCDISTRIBUTIONFLOWELEMENTTYPE");
		schema.AddRelationType("IFCFLOWSEGMENT", "IFCFLOWSEGMENTTYPE");
		schema.AddRelationType("IFCFLOWSTORAGEDEVICE", "IFCFLOWSTORAGEDEVICETYPE");
		schema.AddRelationType("IFCTRANSPORTELEMENT", "IFCTRANSPORTELEMENTTYPE");
		schema.AddRelationType("IFCDOOR", "IFCDOORSTYLE");
		schema.AddRelationType("IFCWINDOW", "IFCWINDOWSTYLE");
	}

}