// <auto-generated/>
// This code was automatically generated with information from Xbim.Essentials 5.9.0.408.
// Any changes made to this file will be lost.

using System;
using System.Collections.Generic;

namespace IdsLib.IfcSchema
{
    public partial class SchemaInfo
    {
        /// <summary>
        /// The names of classes across all schemas.
        /// </summary>
        public static IEnumerable<IfcMeasureInformation> AllMeasures
        {
            get
            {
               yield return new IfcMeasureInformation("IfcAmountOfSubstanceMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcAreaDensityMeasure", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcAreaMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcBinary", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcBoolean", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcDate", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcDateTime", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcDescriptiveMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcDuration", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcDynamicViscosityMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcElectricCapacitanceMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcElectricChargeMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcElectricConductanceMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcElectricCurrentMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcElectricResistanceMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcElectricVoltageMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcEnergyMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcFontStyle", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcFontVariant", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcFontWeight", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcForceMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcFrequencyMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcGloballyUniqueId", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcHeatFluxDensityMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcHeatingValueMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcIdentifier", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcIlluminanceMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcInteger", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcIonConcentrationMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcIsothermalMoistureCapacityMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcLabel", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcLengthMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcLinearVelocityMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcLogical", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcLuminousFluxMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcLuminousIntensityMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcMassDensityMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcMassFlowRateMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcMassMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcMassPerLengthMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcModulusOfElasticityMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcMoistureDiffusivityMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcMolecularWeightMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcMomentOfInertiaMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcPHMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcPlanarForceMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcPlaneAngleMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcPositiveInteger", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcPowerMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcPresentableText", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcPressureMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcRadioActivityMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcRatioMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcReal", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcRotationalFrequencyMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcSectionModulusMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcSoundPowerMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcSoundPressureMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcSpecificHeatCapacityMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcTemperatureRateOfChangeMeasure", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcText", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcTextAlignment", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcTextDecoration", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcTextFontName", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcTextTransformation", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcThermalConductivityMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcThermalTransmittanceMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcThermodynamicTemperatureMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcTime", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcTimeMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcTimeStamp", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcTorqueMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcURIReference", new[] { "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcVaporPermeabilityMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcVolumeMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcVolumetricFlowRateMeasure", new[] { "Ifc2x3", "Ifc4", "Ifc4x3" });
               yield return new IfcMeasureInformation("IfcWellKnownTextLiteral", new[] { "Ifc4x3" });
            }
        }
    }
}

