// <auto-generated/>
// This code was automatically generated with information from Xbim.Essentials 6.0.517.0.
// Any changes made to this file will be lost.

using System;
using System.Collections.Generic;

namespace IdsLib.IfcSchema;

public partial class SchemaInfo
{
	private static readonly IfcConversionUnitInformation[] _conversionUnits = [
		new IfcConversionUnitInformation("inch", "IFCLENGTHMEASURE", 25.4, "mm"),
		new IfcConversionUnitInformation("foot", "IFCLENGTHMEASURE", 304.8, "mm"),
		new IfcConversionUnitInformation("US survey foot", "IFCLENGTHMEASURE", 304.80060960122, "mm"),
		new IfcConversionUnitInformation("yard", "IFCLENGTHMEASURE", 914, "mm"),
		new IfcConversionUnitInformation("mile", "IFCLENGTHMEASURE", 1609, "m"),
		new IfcConversionUnitInformation("square inch", "IFCAREAMEASURE", 0.0006452, "square meter"),
		new IfcConversionUnitInformation("square foot", "IFCAREAMEASURE", 0.09290, "square meter"),
		new IfcConversionUnitInformation("square yard", "IFCAREAMEASURE", 0.83612736, "square meter"),
		new IfcConversionUnitInformation("acre", "IFCAREAMEASURE", 4046.86, "square meter"),
		new IfcConversionUnitInformation("square mile", "IFCAREAMEASURE", 2588881, "square meter"),
		new IfcConversionUnitInformation("cubic inch", "IFCVOLUMEMEASURE", 0.00001639, "cubic meter"),
		new IfcConversionUnitInformation("cubic foot", "IFCVOLUMEMEASURE", 0.02832, "cubic meter"),
		new IfcConversionUnitInformation("cubic yard", "IFCVOLUMEMEASURE", 0.7636, "cubic meter"),
		new IfcConversionUnitInformation("litre", "IFCVOLUMEMEASURE", 0.001, "cubic meter"),
		new IfcConversionUnitInformation("fluid ounce UK", "IFCVOLUMEMEASURE", 0.0000284130625, "cubic meter"),
		new IfcConversionUnitInformation("fluid ounce US", "IFCVOLUMEMEASURE", 0.00002957353, "cubic meter"),
		new IfcConversionUnitInformation("pint UK", "IFCVOLUMEMEASURE", 0.000568, "cubic meter"),
		new IfcConversionUnitInformation("pint US", "IFCVOLUMEMEASURE", 0.000473, "cubic meter"),
		new IfcConversionUnitInformation("gallon UK", "IFCVOLUMEMEASURE", 0.004546, "cubic meter"),
		new IfcConversionUnitInformation("gallon US", "IFCVOLUMEMEASURE", 0.003785, "cubic meter"),
		new IfcConversionUnitInformation("degree", "IFCPLANEANGLEMEASURE", 0.017453292519943295, "rad"),
		new IfcConversionUnitInformation("ounce", "IFCMASSMEASURE", 28.35, "g"),
		new IfcConversionUnitInformation("pound", "IFCMASSMEASURE", 0.454, "kg"),
		new IfcConversionUnitInformation(["ton UK", "long ton", "gross ton", "shipper's ton"], "IFCMASSMEASURE", 1016.0469088, "kg", null),
		new IfcConversionUnitInformation(["ton US", "short ton", "net ton"], "IFCMASSMEASURE", 907.18474, "kg", null),
		new IfcConversionUnitInformation(["lbf", "pound-force"], "IFCFORCEMEASURE", 4.4482216153, "N", null),
		new IfcConversionUnitInformation(["kip", "kilopound-force"], "IFCFORCEMEASURE", 4448.2216153, "N", null),
		new IfcConversionUnitInformation(["psi", "pound-force per square inch"], "IFCPRESSUREMEASURE", 6894.7572932, "Pa", null),
		new IfcConversionUnitInformation(["ksi", "kilopound-force per square inch"], "IFCPRESSUREMEASURE", 6894757.2932, "Pa", null),
		new IfcConversionUnitInformation("minute", "IFCTIMEMEASURE", 60, "s"),
		new IfcConversionUnitInformation("hour", "IFCTIMEMEASURE", 3600, "s"),
		new IfcConversionUnitInformation("day", "IFCTIMEMEASURE", 86400, "s"),
		new IfcConversionUnitInformation(["btu", "British Thermal Unit"], "IFCENERGYMEASURE", 1055.056, "J", null),
		new IfcConversionUnitInformation("mm", "IFCLENGTHMEASURE", 0.001, "m"),
		new IfcConversionUnitInformation("g", "IFCMASSMEASURE", 0.001, "kg"),
		new IfcConversionUnitInformation("square meter", "IFCAREAMEASURE", 1, "m2"),
		new IfcConversionUnitInformation("cubic meter", "IFCVOLUMEMEASURE", 1, "m3"),
		new IfcConversionUnitInformation("Kg", "IFCMASSMEASURE", 1, "kg"),
		new IfcConversionUnitInformation(["°F", "Fahrenheit"], "IFCTHERMODYNAMICTEMPERATUREMEASURE", 0.5555555555555556, "°K", 459.67),
		new IfcConversionUnitInformation(["°C", "Celsius"], "IFCTHERMODYNAMICTEMPERATUREMEASURE", 1, "°K", 273.15),
		];

	/// <summary>
	/// Some standard unit conversions found in IFC files, including those defined in the buildingSMART documentation
	/// </summary>
	public static IEnumerable<IfcConversionUnitInformation> StandardConversionUnits => _conversionUnits;
}