// <auto-generated/>
// This code was automatically generated with information from Xbim.Essentials 6.0.587.0.
// Any changes made to this file will be lost.

using System;
using System.Collections.Generic;

namespace IdsLib.IfcSchema;

/// <summary>
/// Mapping information for an entity mapping from an IFC4 class to the equivalent IFC2x3 class and type, 
/// as documented by buildingSMART in the ifc2x3-occurrence-type-mapping-table.md file.
/// 
/// For example, the definition of an IDS applicability facet with entity `IfcFilter`, 
/// should result in the identification of all `IfcFlowTreatmentDevice` in the model 
/// that are associated with a type `IfcFilterType`.
/// </summary>
public class Ifc2x3EntityMappingInformation
{
	/// <summary>
	/// Entity name as identified by the IDS file (not a valid IFC2x3 entity name)
	/// </summary>
	public string IdsEntity { get; }
	/// <summary>
	/// Entity name of the IFC occurrences in the IFC2x3 schema (valid IFC2x3 entity name).
	/// Filters need to include the type, so that only occurrences belonging to type <see cref="IfcEntityType"/> are included in the mapping.
	/// </summary>
	public string IfcEntity { get; }
	/// <summary>
	/// Type name of the IFC occurrences in the IFC2x3 schema (valid IFC2x3 entity type name).
	/// </summary>
	public string IfcEntityType { get; }

	/// <summary>
	/// Initializing constructor for the mapping information, with trimming of the input strings
	/// </summary>
	public Ifc2x3EntityMappingInformation(string sourceEntity, string mappedEntity, string mappedType)
	{
		IdsEntity = sourceEntity.Trim();
		IfcEntity = mappedEntity.Trim();
		IfcEntityType = mappedType.Trim();
	}
}

public partial class SchemaInfo
{
	private static readonly Ifc2x3EntityMappingInformation[] _ifc2x3SchemaMaps = [
		new Ifc2x3EntityMappingInformation("IfcFurniture", "IfcFurnishingElement", "IfcFurnitureType"),
		new Ifc2x3EntityMappingInformation("IfcSystemFurnitureElement", "IfcFurnishingElement", "IfcSystemFurnitureElementType"),
		new Ifc2x3EntityMappingInformation("IfcActuator", "IfcDistributionControlElement", "IfcActuatorType"),
		new Ifc2x3EntityMappingInformation("IfcAlarm", "IfcDistributionControlElement", "IfcAlarmType"),
		new Ifc2x3EntityMappingInformation("IfcController", "IfcDistributionControlElement", "IfcControllerType"),
		new Ifc2x3EntityMappingInformation("IfcFlowInstrument", "IfcDistributionControlElement", "IfcFlowInstrumentType"),
		new Ifc2x3EntityMappingInformation("IfcSensor", "IfcDistributionControlElement", "IfcSensorType"),
		new Ifc2x3EntityMappingInformation("IfcAirToAirHeatRecovery", "IfcEnergyConversionDevice", "IfcAirToAirHeatRecoveryType"),
		new Ifc2x3EntityMappingInformation("IfcBoiler", "IfcEnergyConversionDevice", "IfcBoilerType"),
		new Ifc2x3EntityMappingInformation("IfcChiller", "IfcEnergyConversionDevice", "IfcChillerType"),
		new Ifc2x3EntityMappingInformation("IfcCoil", "IfcEnergyConversionDevice", "IfcCoilType"),
		new Ifc2x3EntityMappingInformation("IfcCondenser", "IfcEnergyConversionDevice", "IfcCondenserType"),
		new Ifc2x3EntityMappingInformation("IfcCooledBeam", "IfcEnergyConversionDevice", "IfcCooledBeamType"),
		new Ifc2x3EntityMappingInformation("IfcCoolingTower", "IfcEnergyConversionDevice", "IfcCoolingTowerType"),
		new Ifc2x3EntityMappingInformation("IfcElectricGenerator", "IfcEnergyConversionDevice", "IfcElectricGeneratorType"),
		new Ifc2x3EntityMappingInformation("IfcElectricMotor", "IfcEnergyConversionDevice", "IfcElectricMotorType"),
		new Ifc2x3EntityMappingInformation("IfcEvaporativeCooler", "IfcEnergyConversionDevice", "IfcEvaporativeCoolerType"),
		new Ifc2x3EntityMappingInformation("IfcEvaporator", "IfcEnergyConversionDevice", "IfcEvaporatorType"),
		new Ifc2x3EntityMappingInformation("IfcHeatExchanger", "IfcEnergyConversionDevice", "IfcHeatExchangerType"),
		new Ifc2x3EntityMappingInformation("IfcHumidifier", "IfcEnergyConversionDevice", "IfcHumidifierType"),
		new Ifc2x3EntityMappingInformation("IfcMotorConnection", "IfcEnergyConversionDevice", "IfcMotorConnectionType"),
		new Ifc2x3EntityMappingInformation("IfcSpaceHeater", "IfcEnergyConversionDevice", "IfcSpaceHeaterType"),
		new Ifc2x3EntityMappingInformation("IfcTransformer", "IfcEnergyConversionDevice", "IfcTransformerType"),
		new Ifc2x3EntityMappingInformation("IfcTubeBundle", "IfcEnergyConversionDevice", "IfcTubeBundleType"),
		new Ifc2x3EntityMappingInformation("IfcUnitaryEquipment", "IfcEnergyConversionDevice", "IfcUnitaryEquipmentType"),
		new Ifc2x3EntityMappingInformation("IfcAirTerminalBox", "IfcFlowController", "IfcAirTerminalBoxType"),
		new Ifc2x3EntityMappingInformation("IfcDamper", "IfcFlowController", "IfcDamperType"),
		new Ifc2x3EntityMappingInformation("IfcElectricTimeControl", "IfcFlowController", "IfcElectricTimeControlType"),
		new Ifc2x3EntityMappingInformation("IfcFlowMeter", "IfcFlowController", "IfcFlowMeterType"),
		new Ifc2x3EntityMappingInformation("IfcProtectiveDevice", "IfcFlowController", "IfcProtectiveDeviceType"),
		new Ifc2x3EntityMappingInformation("IfcSwitchingDevice", "IfcFlowController", "IfcSwitchingDeviceType"),
		new Ifc2x3EntityMappingInformation("IfcValve", "IfcFlowController", "IfcValveType"),
		new Ifc2x3EntityMappingInformation("IfcCableCarrierFitting", "IfcFlowFitting", "IfcCableCarrierFittingType"),
		new Ifc2x3EntityMappingInformation("IfcDuctFitting", "IfcFlowFitting", "IfcDuctFittingType"),
		new Ifc2x3EntityMappingInformation("IfcJunctionBox", "IfcFlowFitting", "IfcJunctionBoxType"),
		new Ifc2x3EntityMappingInformation("IfcPipeFitting", "IfcFlowFitting", "IfcPipeFittingType"),
		new Ifc2x3EntityMappingInformation("IfcCompressor", "IfcFlowMovingDevice", "IfcCompressorType"),
		new Ifc2x3EntityMappingInformation("IfcFan", "IfcFlowMovingDevice", "IfcFanType"),
		new Ifc2x3EntityMappingInformation("IfcPump", "IfcFlowMovingDevice", "IfcPumpType"),
		new Ifc2x3EntityMappingInformation("IfcCableCarrierSegment", "IfcFlowSegment", "IfcCableCarrierSegmentType"),
		new Ifc2x3EntityMappingInformation("IfcCableSegment", "IfcFlowSegment", "IfcCableSegmentType"),
		new Ifc2x3EntityMappingInformation("IfcDuctSegment", "IfcFlowSegment", "IfcDuctSegmentType"),
		new Ifc2x3EntityMappingInformation("IfcPipeSegment", "IfcFlowSegment", "IfcPipeSegmentType"),
		new Ifc2x3EntityMappingInformation("IfcElectricFlowStorageDevice", "IfcFlowStorageDevice", "IfcElectricFlowStorageDeviceType"),
		new Ifc2x3EntityMappingInformation("IfcTank", "IfcFlowStorageDevice", "IfcTankType"),
		new Ifc2x3EntityMappingInformation("IfcAirTerminal", "IfcFlowTerminal", "IfcAirTerminalType"),
		new Ifc2x3EntityMappingInformation("IfcElectricAppliance", "IfcFlowTerminal", "IfcElectricApplianceType"),
		new Ifc2x3EntityMappingInformation("IfcFireSuppressionTerminal", "IfcFlowTerminal", "IfcFireSuppressionTerminalType"),
		new Ifc2x3EntityMappingInformation("IfcLamp", "IfcFlowTerminal", "IfcLampType"),
		new Ifc2x3EntityMappingInformation("IfcLightFixture", "IfcFlowTerminal", "IfcLightFixtureType"),
		new Ifc2x3EntityMappingInformation("IfcOutlet", "IfcFlowTerminal", "IfcOutletType"),
		new Ifc2x3EntityMappingInformation("IfcSanitaryTerminal", "IfcFlowTerminal", "IfcSanitaryTerminalType"),
		new Ifc2x3EntityMappingInformation("IfcStackTerminal", "IfcFlowTerminal", "IfcStackTerminalType"),
		new Ifc2x3EntityMappingInformation("IfcWasteTerminal", "IfcFlowTerminal", "IfcWasteTerminalType"),
		new Ifc2x3EntityMappingInformation("IfcDuctSilencer", "IfcFlowTreatmentDevice", "IfcDuctSilencerType"),
		new Ifc2x3EntityMappingInformation("IfcFilter", "IfcFlowTreatmentDevice", "IfcFilterType"),
		new Ifc2x3EntityMappingInformation("IfcVibrationIsolator", "IfcEquipmentElement", "IfcVibrationIsolatorType"),
		];

	/// <summary>
	/// Provides a list of IDS entity names that need to be remapped when dealing with IFC2x3 schema.
	/// See <see cref="Ifc2x3EntityMappingInformation"/> for more information on the mapping and its intended use.
	/// </summary>
	public static IEnumerable<Ifc2x3EntityMappingInformation> Ifc2x3SpecialEntityMaps => _ifc2x3SchemaMaps;
}