using System.Runtime.InteropServices.JavaScript;
using System.Text;

namespace IdsLib.codegen;
internal class IdsSchema_RestrictionTypeGenerator
{
	// originally taken from: https://www.w3.org/TR/xmlschema-2/ with some adjustments based on IDS specification documents
	// (e.g., we don't need to support all types)
	// "totalDigits" and "fractionDigits" removed from integer and decimal
	internal static Dictionary<string, string[]> validConstraintsDictionary = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase)
	{
		{"XsString", ["annotation", "pattern", "enumeration", "minLength", "maxLength", "length"] },
		{"XsAnyUri", ["annotation", "pattern", "enumeration", "minLength", "maxLength", "length"] },
		{"XsDouble", ["annotation", "pattern", "enumeration", "minExclusive", "maxExclusive", "minInclusive", "maxInclusive"] },
		{"XsFloat", ["annotation", "pattern", "enumeration", "minExclusive", "maxExclusive", "minInclusive", "maxInclusive"] },
		{"XsDuration", ["annotation", "pattern", "enumeration", "minExclusive", "maxExclusive", "minInclusive", "maxInclusive"] },
		{"XsDateTime", ["annotation", "pattern", "enumeration", "minExclusive", "maxExclusive", "minInclusive", "maxInclusive"] },
		{"XsTime", ["annotation", "pattern", "enumeration", "minExclusive", "maxExclusive", "minInclusive", "maxInclusive"] },
		{"XsDate", ["annotation", "pattern", "enumeration", "minExclusive", "maxExclusive", "minInclusive", "maxInclusive"] },
		{"XsDecimal", ["annotation", "pattern", "enumeration", "minExclusive", "maxExclusive", "minInclusive", "maxInclusive"] },
		{"XsBoolean", ["annotation", "pattern"] },
		{"XsInteger", ["annotation", "pattern", "enumeration", "maxInclusive", "maxExclusive", "minInclusive", "minExclusive"] },
	};

	internal static string Execute(out Dictionary<string, string[]> dataTypeDictionary)
	{
		dataTypeDictionary = validConstraintsDictionary;
		var sbDataTypes = new StringBuilder();
		foreach ( var dataType in validConstraintsDictionary.Keys )
		{
			var val = validConstraintsDictionary[dataType];	
			var valsAsString = string.Join(", ", val.Select(v => $"\"{v}\""));
			sbDataTypes.AppendLine($"\t\t{{XsTypes.BaseTypes.{dataType}, [{valsAsString}] }},");
		}

		var source = stub;
		source = source.Replace($"<PlaceHolderDataTypes>", sbDataTypes.ToString().TrimEnd('\r', '\n'));			
		return source;
		// Program.Message($"no change.", ConsoleColor.Green);
	}

	private const string stub = """
		// <auto-generated/>
		// This code was automatically generated 
		// Any changes made MANUALLY to this file will be lost.
		
		using System;
		using System.Collections.Generic;
		using System.Text;

		namespace IdsLib.IdsSchema.XsNodes;

		internal partial class XsRestriction
		{
			private static Dictionary<XsTypes.BaseTypes, List<string>> validConstraintsDictionary = new Dictionary<XsTypes.BaseTypes, List<string>>()
			{
		<PlaceHolderDataTypes>
			};
		}

		""";
}