using System.Diagnostics;
using System.Text;
using Xbim.Common.Metadata;

namespace IdsLib.codegen;

public class IfcSchema_PartOfRelationGenerator
{
    internal static string Execute()
    {
        var relationNames = GetRelationNames();

        var schemaInfos = new Dictionary<string, StringBuilder>();
        foreach (var schema in Program.schemas)
        {
            var sb = new StringBuilder();
			var module = SchemaHelper.GetFactory(schema);
			var metaD = ExpressMetaData.GetMetadata(module);
            foreach (var daRelation in relationNames)
			{
				var relationChainNames = daRelation.Split(' ').Reverse().ToArray();
				GetMultipleRelationChain(metaD, relationChainNames, out var manySide, out var oneSide);
				// sb.AppendLine($"""                yield return new PartOfRelationInformation("{daRelation}", "{ownerExpressType.Name.ToUpperInvariant()}", "{partExpressType.Name.ToUpperInvariant()}");""");
				sb.AppendLine($"""                yield return new PartOfRelationInformation("{daRelation}", "{oneSide.ToUpperInvariant()}", "{manySide.ToUpperInvariant()}");""");

			}
			schemaInfos.Add(schema.ToString(), sb);
        }
        var source = stub;
        foreach (var schema in schemaInfos.Keys.OrderBy(x => x))
        {
			source = source.Replace($"<PlaceHolderRelations{schema}>\r\n", schemaInfos[schema].ToString());
        }
        
        source = source.Replace($"<PlaceHolderVersion>", VersionHelper.GetFileVersion(typeof(ExpressMetaData)));
        return source;
    }

	private static void GetMultipleRelationChain(ExpressMetaData metaD, string[] relationChainNames, out string manySide, out string oneSide)
	{
		oneSide = string.Empty;
		// Debug.WriteLine($"Iterating relation type: {string.Join(",", relationChainNames)} for {metaD.Module.Name}");
		manySide = GetManySide(metaD, GetExpress(metaD, relationChainNames[0])); // get the many side of the first relation in the chain
		oneSide = GetOneSide(metaD, relationChainNames[relationChainNames.Length - 1]); // get the one side of the last relation in the chain
	}

	private static string GetOneSide(ExpressMetaData metaD, string iteratingRelationType)
	{
		// Debug.WriteLine($"    Searching for one side by 'Relating' name");
		var propOnOneSide = GetExpress(metaD, iteratingRelationType).GetRelevantProperties().Single(x => x.EnumerableType is null && x.Name.StartsWith("Relating"));
		return propOnOneSide.GetExpressTypeDefinition()?.ToUpper() ?? "";
	}

	private static string GetManySide(ExpressMetaData metaD, ExpressType relationType)
	{
		// Debug.WriteLine($"    searching for many side by single enumerable type");
		var propOnManySide = relationType.GetRelevantProperties().SingleOrDefault(x => x.EnumerableType is not null);
		if (propOnManySide is not null)
			return propOnManySide.GetExpressTypeDefinition(XbimHelper.IncludeBuildParameters.ProcessEnumerables)?.ToUpper() ?? "";
		// Debug.WriteLine($"    searching for many side by single 'Related' name");
		propOnManySide = relationType.GetRelevantProperties().Single(x => x.EnumerableType is null && x.Name.StartsWith("Related"));
		if (propOnManySide is not null)
			return propOnManySide.GetExpressTypeDefinition(XbimHelper.IncludeBuildParameters.ProcessSingleValues)?.ToUpper() ?? "";
		return "";
	}

	private static ExpressType GetExpress(ExpressMetaData metaD, string iteratingRelationType)
	{
		// Debug.WriteLine($"  Iterating relation type: {iteratingRelationType}");
		var relationType = metaD.ExpressType(iteratingRelationType.ToUpperInvariant());
		if (relationType is null)
			throw new InvalidOperationException($"Relation type not found: {iteratingRelationType}");
		return relationType;
	}

	private static IEnumerable<string> GetRelationNames()
    {
        yield return "IFCRELAGGREGATES";
        yield return "IFCRELASSIGNSTOGROUP";
        yield return "IFCRELCONTAINEDINSPATIALSTRUCTURE";
        yield return "IFCRELNESTS";
        yield return "IFCRELVOIDSELEMENT IFCRELFILLSELEMENT";
    }

    private const string stub = """
		// <auto-generated/>
		// This code was automatically generated with information from Xbim.Essentials <PlaceHolderVersion>.
		// Any changes made to this file will be lost.

		using System;
		using System.Collections.Generic;

		namespace IdsLib.IfcSchema;

		public partial class SchemaInfo
		{
		    /// <summary>
		    /// The names of classes across all schemas.
		    /// </summary>
		    public IEnumerable<PartOfRelationInformation> AllPartOfRelations
		    {
		        get
		        {
		            if (Version == IfcSchemaVersions.Ifc2x3)
		            {
		<PlaceHolderRelationsIfc2x3>
		            }
		            if (Version == IfcSchemaVersions.Ifc4)
		            {
		<PlaceHolderRelationsIfc4>
		            }
		            if (Version == IfcSchemaVersions.Ifc4x3)
		            {
		<PlaceHolderRelationsIfc4x3>
		            }
		        }
		    }
		}

		""";
}
