using System.Text;
using Xbim.Common.Metadata;

namespace IdsLib.codegen;

public class IfcSchema_PartOfRelationGenerator
{
    internal static string Execute()
    {
        var relationNames = GetRelationNames();

        var schemaInfos = new Dictionary<string, StringBuilder>();
        foreach (var schema in Program.schemas)
        {
            var sb = new StringBuilder();
			var module = SchemaHelper.GetFactory(schema);
			var metaD = ExpressMetaData.GetMetadata(module);
            foreach (var daRelation in relationNames)
            {
                try
                {
					var partNames = daRelation.Split(' ');
					string manySide = string.Empty;
					string oneSide = string.Empty;
					foreach (var partName in partNames.Reverse())
					{
						var t = metaD.ExpressType(partName.ToUpperInvariant());
						if (t is null)
							continue;
						
						if (string.IsNullOrEmpty(manySide)) // if the starting point has been assigned, we can avoid its search
						{
							var propOnManySide = t.GetRelevantProperties().SingleOrDefault(x => x.EnumerableType is not null);
							Type? manySideType = null;
							if (propOnManySide is not null)
							{
								manySideType = propOnManySide.EnumerableType;
							}
							else
							{
								propOnManySide = t.GetRelevantProperties().Single(x => x.EnumerableType is null && x.Name.StartsWith("Related"));
								manySideType = propOnManySide.PropertyInfo.PropertyType;
							}
							var manySideExpressType = metaD.ExpressType(manySideType.Name.ToUpperInvariant());
							manySide = manySideExpressType.Name.ToUpperInvariant();
						}
						var propOnOneSide = t.GetRelevantProperties().Single(x => x.EnumerableType is null && x.Name.StartsWith("Relating"));
						var oneSideType = propOnOneSide.PropertyInfo.PropertyType;
						var oneSideExpressType = metaD.ExpressType(oneSideType.Name.ToUpperInvariant());
						oneSide = oneSideExpressType.Name.ToUpperInvariant();
					}
					// sb.AppendLine($"""                yield return new PartOfRelationInformation("{daRelation}", "{ownerExpressType.Name.ToUpperInvariant()}", "{partExpressType.Name.ToUpperInvariant()}");""");
					sb.AppendLine($"""                yield return new PartOfRelationInformation("{daRelation}", "{oneSide.ToUpperInvariant()}", "{manySide.ToUpperInvariant()}");""");
                }
                catch 
                {
                    continue;
                }                
            }
            schemaInfos.Add(schema.ToString(), sb);
        }
        var source = stub;
        foreach (var schema in schemaInfos.Keys.OrderBy(x => x))
        {
			source = source.Replace($"<PlaceHolderRelations{schema}>\r\n", schemaInfos[schema].ToString());
        }
        
        source = source.Replace($"<PlaceHolderVersion>", VersionHelper.GetFileVersion(typeof(ExpressMetaData)));
        return source;
    }

    private static IEnumerable<string> GetRelationNames()
    {
        yield return "IFCRELAGGREGATES";
        yield return "IFCRELASSIGNSTOGROUP";
        yield return "IFCRELCONTAINEDINSPATIALSTRUCTURE";
        yield return "IFCRELNESTS";
        yield return "IFCRELVOIDSELEMENT IFCRELFILLSELEMENT";
    }

    private const string stub = """
		// <auto-generated/>
		// This code was automatically generated with information from Xbim.Essentials <PlaceHolderVersion>.
		// Any changes made to this file will be lost.

		using System;
		using System.Collections.Generic;

		namespace IdsLib.IfcSchema;

		public partial class SchemaInfo
		{
		    /// <summary>
		    /// The names of classes across all schemas.
		    /// </summary>
		    public IEnumerable<PartOfRelationInformation> AllPartOfRelations
		    {
		        get
		        {
		            if (Version == IfcSchemaVersions.Ifc2x3)
		            {
		<PlaceHolderRelationsIfc2x3>
		            }
		            if (Version == IfcSchemaVersions.Ifc4)
		            {
		<PlaceHolderRelationsIfc4>
		            }
		            if (Version == IfcSchemaVersions.Ifc4x3)
		            {
		<PlaceHolderRelationsIfc4x3>
		            }
		        }
		    }
		}

		""";
}
