using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IdsLib.codegen
{
	internal class XmlSchema_XsTypesGenerator
	{
		internal static string Execute(Dictionary<string, typeMetadata> dataTypeDictionary)
		{
			var sbXmlTypes = new StringBuilder();
			var sbXmlTypeRegexStrings = new StringBuilder();
			var sbXmlTypeFacets = new StringBuilder();

			var xmlTypes = dataTypeDictionary.Values.Select(x => x.XmlBackingType).Where(str => !string.IsNullOrWhiteSpace(str)).Distinct();
			foreach (var dataType in xmlTypes.OrderBy(x => x))
			{
				var t = XmlSchema_XsTypesGenerator.GetRegexString(dataType);
				var name = dataType.Replace("xs:", "");
				name = name[..1].ToUpper() + name[1..];
				sbXmlTypeRegexStrings.AppendLine($"\t\t\t\tBaseTypes.Xs{name} => @\"{t}\",");

				if (!IdsSchema_RestrictionTypeGenerator.validConstraintsDictionary.TryGetValue($"Xs{name}", out var facets))
				{
					Program.Message($"no facets found for {name}, this should not happen, check the validConstraintsDictionary in IdsSchema_RestrictionTypeGenerator.", ConsoleColor.Yellow);
				}
				else
				{
					var facetChecks = facets.Select(f => GetXsdFacetEnumName(f));
					var facetChecksString = string.Join(", ", facetChecks);
					sbXmlTypeFacets.AppendLine($"\t\t\t\tBaseTypes.Xs{name} => [{facetChecksString}],");
				}


				if (string.IsNullOrWhiteSpace(t))
					continue;
				sbXmlTypes.AppendLine($"\t\tprivate readonly static Regex regex{name} = new(@\"{t}\", RegexOptions.Compiled);");
			}

			var source = stub;
			source = source.Replace($"<PlaceHolderXmlRegexes>", sbXmlTypes.ToString().TrimEnd('\r', '\n'));
			source = source.Replace($"<PlaceHolderXmlRegexStrings>", sbXmlTypeRegexStrings.ToString().TrimEnd('\r', '\n'));
			source = source.Replace($"<PlaceHolderFacets>", sbXmlTypeFacets.ToString().TrimEnd('\r', '\n'));
			return source;
		}

		private static string GetXsdFacetEnumName(string xsdFacetName)
		{
			return $"XsdAllowedFacets." + xsdFacetName[0..1].ToUpperInvariant() + xsdFacetName[1..];
		}

		/// <summary>
		/// this is also used for the documentation
		/// </summary>		
		internal static string GetRegexString(string dataType)
		{
			return dataType switch
			{
				"xs:boolean" => @"^(true|false|0|1)$",
				"xs:date" => @"^\d{4}-\d{2}-\d{2}(Z|([+-]\d{2}:\d{2}))?$",
				"xs:dateTime" => @"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|([+-]\d{2}:\d{2}))?$",
				"xs:double" => @"^([-+]?[0-9]*\.?[0-9]*([eE][-+]?[0-9]+)?|NaN|\+INF|-INF)$",
				"xs:duration" => @"^[-+]?P(\d+Y)?(\d+M)?(\d+D)?(T(\d+H)?(\d+M)?(\d+S)?)?$",
				"xs:integer" => @"^[+-]?(\d+)$",
				"xs:string" => @"^.*$",
				"xs:anyUri" => @"^\S+$", // This roughly matches the practical behavior of many validators: “any non-empty, non-whitespace string”.  Use of spaces is highly discouraged (unless they are encoded by %20).
				"xs:time" => @"^\d{2}:\d{2}:\d{2}(\.\d+)?(Z|([+-]\d{2}:\d{2}))?$",
				_ => ""
			};
		}

		private const string stub =
			"""
			// <auto-generated/>
			// This code was automatically generated.
			// Any changes made to this file will be lost.

			using System.Text.RegularExpressions;

			namespace IdsLib.IdsSchema.XsNodes
			{
				public static partial class XsTypes
				{
			<PlaceHolderXmlRegexes>

					/// <summary>
					/// Returns the regular expression pattern string associated with the specified base type.
					/// </summary>
					/// <param name="requiredType">The base type for which to retrieve the regular expression pattern.</param>
					/// <returns>
					/// A string containing the regular expression pattern for the specified base type. 
					/// Returns an empty string if no
					/// pattern is defined for the given type.
					/// </returns>
					public static string GetRegexString(BaseTypes requiredType)
					{
						return requiredType switch
						{
			<PlaceHolderXmlRegexStrings>
							_ => ""
						};
					}
						
					/// <summary>
					/// Returns the set of XSD facets that are allowed for the specified base type.
					/// </summary>
					/// <param name="requiredType">The base type for which to retrieve the allowed XSD facets.</param>
					/// <returns>An array of XsdAllowedFacets values representing the facets permitted for the specified base type. The array is
					/// empty if no facets are allowed.</returns>
					public static XsdAllowedFacets[] GetAllowedFacets(BaseTypes requiredType)
					{
						return requiredType switch
						{
			<PlaceHolderFacets>
							_ => []
						};
					}

				}
			}
			""";
	}
}
